# Generated by Django 5.2.7 on 2025-10-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_job_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('provider', models.CharField()),
                ('description', models.CharField()),
                ('duration', models.DurationField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
