# Generated by Django 5.2.7 on 2025-10-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('provider', models.CharField()),
                ('description', models.CharField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
