# Generated by Django 5.2.7 on 2025-10-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_application_bookmarked_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
