# Generated by Django 5.2.7 on 2025-11-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_job_owner_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='owner',
        ),
    ]
