# Generated by Django 5.2.7 on 2025-11-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_application_bookmarked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
