# Generated by Django 5.2.7 on 2025-11-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_bookmark_is_bookmarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='is_favorite',
            field=models.BooleanField(default=True),
        ),
    ]
