# Generated by Django 5.2.7 on 2025-11-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_bookmark_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootcamp',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='bootcamp',
            name='start_date',
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open'),
        ),
    ]
