# Generated by Django 5.2.7 on 2025-11-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_bootcamp_end_date_remove_bootcamp_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
